#!/usr/bin/env bash
# This script creates a PID file, displays messages, and handles different signals.
# shellcheck disable=SC2009

# Create the /var/run/myscript.pid file containing the script's PID
echo $$ > /var/run/myscript.pid

# Define the trap actions for the different signals
trap "echo 'I hate the kill command'; exit 0" SIGTERM
trap "echo 'Y U no love me?!'; exit 0" SIGINT
trap "rm -f /var/run/myscript.pid; exit 0" SIGQUIT SIGTERM

# Display "To infinity and beyond" indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2
done

