#!/usr/bin/env bash
# This script stops the '4-to_infinity_and_beyond' process using the 'kill' command in Terminal #0
# shellcheck disable=SC2009

# Get the PID of the process running in Terminal #0 that matches the '4-to_infinity_and_beyond' name
pid=$(pgrep -f "4-to_infinity_and_beyond")

# If the process is found, kill it
if [[ -n "$pid" ]]; then
    kill "$pid"
    echo "Process with PID $pid has been stopped."
else
    echo "No process found for '4-to_infinity_and_beyond'."
fi
