#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely, with a sleep 2 in between each iteration.
# When receiving a SIGTERM signal, it displays "I am invincible!!!"
# shellcheck disable=SC2009

trap "echo 'I am invincible!!!'; exit 0" SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
