#!/usr/bin/env bash
# Bash script that displays the content of the file 
while IFS=: read -r username _ userid _ _ home _; do
  echo "Username: $username"
  echo "User ID: $userid"
  echo "Home Directory: $home"
  echo
done < /etc/passwd
