#!/usr/bin/env bash
# Bash script that displays the content of the file
while IFS=: read -r username _ userid group _ _ home shell; do
  echo "The user $username is part of the $group gang, lives in $home and rides $shell."
  echo "USER ID's place is protected by the passcode $userid, more info about the user here: $group"
  echo
done < /etc/passwd
